language: php

php:
  - 7.3
  - 7.4
  - 8.0

install: composer install

script:
  - vendor/bin/phpstan analyse --no-interaction --no-progress
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage_clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email:
    - sam@badcow.co